FROM debian:trixie

RUN apt-get update && apt-get install -y \
    bison \
    build-essential \
    curl \
    file \
    gawk \
    git \
    make \
    patchelf \
    procps \
    python3 \
    rsync \
    xxd \
    && rm -rf /var/lib/apt/lists/*
